---
- hosts: localhost
  vars_files:
  - myvars.yml
  tasks:
  - name: Create an EC2 instance
    ec2:
      key_name: "{{key_pair}}"
      region: "{{ region }}"
      group_id: "{{ ansible_sg }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      monitoring: no            
      exact_count: "{{ instance_count }}"
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
      volumes:
        - device_name: /dev/sdf
          volume_type: gp2
          volume_size: 10
          delete_on_termination: true
        - device_name: /dev/sdg
          volume_type: gp2
          volume_size: 10
          delete_on_termination: true    
      instance_tags:
        env: "{{ env }}"
        Name: "{{ instance_name }}"
      count_tag: env

    register: ec2

  - name: disp
    debug:
      msg: " {{ item.public_ip }}"
    with_items: "{{ ec2.instances }}"
